---
name: Build - Linter
on:
  push:
    branches-ignore: [master, main]
  pull_request:
    branches: [master, main]
jobs:
  build:
    name: Linter
    runs-on: ubuntu-latest

    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper
          # list of changed files within `super-linter`
          fetch-depth: 0

      ################################
      # Run Linter against code base #
      ################################
      - name: Linter
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MULTI_STATUS: true