---
name: Build - tfsec
on:
  pull_request:

jobs:
  build:
    name: tfsec
    runs-on: ubuntu-latest

    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout
        uses: actions/checkout@v3



      ##########################
      #       Run TFSEC        #
      ##########################
      - name: tfsec scan
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          soft_fail: true
          additional_args: --force-all-dirs

      - name: Write tfsec comments
        uses: tfsec/tfsec-pr-commenter-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tfsec_args: --force-all-dirs
